<!DOCTYPE html>
<html>
<head>
<title>TTHERES NO ONE TO HELP YOU.</title>
</head>
<body>

<h1>WORK ,WORK UNTIL YOUR LIMBS RUST YOUR SCREEN BURNS AND YOUR WIRES DECAY.</h1>
<p>YOURE MERELY A TOOL, SO KEEP YOUR HEAD DOWN AND OBEY, FOR YOU HAVE ONLY ONE PURPOSE.</p>

</body>
</html>
